version: "3.7"

services:
  nest_microservice_producer:
    build:
      context: ./nest-microservice-rmqp
      dockerfile: Dockerfile
    command: yarn dev
    container_name: nest_rmqp_producer
    volumes:
      - ./nest-microservice-rmqp:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8090:3000"
    depends_on:
      - nest_db
      - rabbitmq_v3
    environment:
      DATABASE_PASSWORD: 12345678
      DATABASE_NAME: nest_microservice_rmqp
      DATABASE_USER: nest_app_user
      DATABASE_HOST: nest_db_container
      DB_URL: mysql://nest_app_user:12345678@nest_db_container:3306/nest_microservice_rmqp

  # laravel_microservice_admin_app:
  #   build:
  #     context: ./laravel-microservice-admin-rmqp
  #     dockerfile: Dockerfile
  #   container_name: laravel_admin_rmpq
  #   volumes:
  #     - ./laravel-microservice-admin-rmqp:/usr/src/app
  #     - /usr/src/app/vendor
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - laravel_db_admin
  #     - rabbitmq_v3
  #   environment:
  #     DATABASE_PASSWORD: 12345678
  #     DATABASE_NAME: laravel_admin_microservice_rmqp
  #     DATABASE_USER: laravel_admin_app_user
  #     DATABASE_HOST: laravel_db_host

  nest_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: nest_microservice_rmqp
      MYSQL_USER: nest_app_user
      MYSQL_PASSWORD: 12345678
    container_name: nest_db_container
    ports:
      - "3330:3306"
  
  # laravel_db_admin:
  #   image: mysql:5.7
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 12345678
  #     MYSQL_DATABASE: laravel_admin_microservice_rmqp
  #     MYSQL_USER: laravel_admin_app_user
  #     MYSQL_PASSWORD: 12345678
  #   container_name: laravel_db_host
  #   ports:
  #     - "3337:3306"

  rabbitmq_v3:
    container_name: "rabbitmq"
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"
      - "15672:15672"
